[package]
name = "cli_deployr"
version = "1.0.0"
edition = "2021"

[lib]
path = "program.rs"

[dependencies]
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["serde_derive"] }
clap = { version = "4.4.11", features = ["derive"] }
pan_lib = { path = "../../lib" }